### ISSUE TITLE
Difference between instance and local variables

### ISSUE THREAD

**Issue by sburtner** [mikejohnson51/geog178#4]
Simple question but just to confirm, local variables are those created inside a method, while an instance variable is available to the whole class and does not require instantiation. In my example below, the instance variables "a" and "b" are created, and "this.a" and "this.b" are local variables created in the Rectangle constructor. Does that sound right?

`double a;
double b;

public Rectangle(double a, double b) {
		this.a = a;
		this.b = b;
	}
`

**Comment by mikejohnson51** [comment]
A couple things, member variables are those that a central to all instances of an object. In this case ALL rectangles have an a and b - the values are just not assigned.

The constructor allows for a new instance of a _particular_ rectangle to be created. The constructor requires that a specific value be assigned for a and b (say 2 and 5). 

2 and 5 then become the a and b values of that specific rectangle but act in the same way as all other a and b value. By adding the 'private' visibility to a and b we make sure that the scope of the variables remains within the the rectangle class

``` java
private double a;
private double b;

public Rectangle(double a, double b) {
this.a = a;
this.b = b;
}
```
Local variables are those that are declared within the body of a method. Only that method can use the variable. Say we wanted a method that always returned 1/2 of a rectangles area (cause I can't think of a better example...

```java
public double getHalf(){

int scale = 2;
double full_area = this.a * this.b;
double half_area = full_area / scale;

return half_area ;

}
```

In this case, scale and full_area are local variables of the getHalf() method.
